"""Primeira versão de Receita

Revision ID: 2e77b27fd7d0
Revises: 
Create Date: 2022-02-26 13:08:03.164496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e77b27fd7d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receitas')),
    sa.UniqueConstraint('titulo', name=op.f('uq_receitas_titulo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receitas')
    # ### end Alembic commands ###
